apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test-eck
  namespace: test-elastic 
spec:
  http:
    tls:
      certificate: {}
      selfSignedCertificate:
        disabled: true
  version: 7.8.0
  nodeSets:
  - count: 1
    name: data-nodes
    config:
      xpack.security.authc.realms: &xpack-realms
        file.file1: 
          order: 0
        native.native1:
          order: 1
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: false
      cluster.remote.connect: false
      thread_pool.write.queue_size: 500
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value:  -Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m