apiVersion:  kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: file-source-connector
  namespace: my-kafka-project
  labels:
    strimzi.io/cluster: connect-cluster-test
spec:
  class: org.apache.kafka.connect.file.FileStreamSourceConnector
  tasksMax: 1
  config:
    file: "/opt/kafka/LICENSE"
    topic: test-new